### PR TITLE
Update1 ocr.py

### PR DESCRIPTION
**Pull request by jay-1307**
This change is [Reviewable](https://reviewable.io/reviews/jay-1307/ocr_project/11)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/jay-1307/OCR_Project/pull/11" target="_blank">ReviewNinja

**Comment by jay-1307** [comment]
cool

**Comment by jay-1307** [comment]
wow

**Comment by jay-1307** [comment]
*[ocr.py, line 4 at r2](https://reviewable.io:443/reviews/jay-1307/ocr_project/11#-Kkzt-Lx80j8dwpPxDhA:-Kkzt-Lx80j8dwpPxDhB:bkl9wus) ([raw file](https://github.com/jay-1307/ocr_project/blob/c27b3e2c62ac1a67ef6bf7648efc5142b5233763/ocr.py#L4)):*
> ```Python
> #just to see whether it saw changes or not
> #made some changes in reviewable
> #getting no change in reviewable, again trying what else can be done
> ```

whats this??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jay-1307/ocr_project/11)*

**Comment by jay-1307** [comment]
*[ocr.py, line 4 at r2](https://reviewable.io:443/reviews/jay-1307/ocr_project/11#-Kkzt-Lx80j8dwpPxDhA:-Kkzt7Zs_bSCc8BZJ748:b-896fix) ([raw file](https://github.com/jay-1307/ocr_project/blob/c27b3e2c62ac1a67ef6bf7648efc5142b5233763/ocr.py#L4)):*
<details><summary><i>Previously, jay-1307 wrote…</i></summary><blockquote>

whats this??
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jay-1307/ocr_project/11)*

**Comment by jay-1307** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jay-1307/ocr_project/11)*

**Comment by jay-1307** [comment]
*[ocr.py, line 5 at r2](https://reviewable.io:443/reviews/jay-1307/ocr_project/11#-Kl-qe2WeNXrNwFd5tUQ:-Kl-qe2WeNXrNwFd5tUR:b-o01lgz) ([raw file](https://github.com/jay-1307/ocr_project/blob/55d67a984266311ebae50f2c95001e7e9a0b609c/ocr.py#L5)):*
>  
> #this file contains the python code of our future ocr project.
> #just to see whether it saw changes or not
> #made some changes in reviewable
> #getting no change in reviewable, again trying what else can be done
> #do I need to pull request?? hello
> #man what is happening
> #i came to know that i can only review changes if I do pull request otherwise not
> #hello,what are doing.
>  
>  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jay-1307/ocr_project/11)*

**Comment by jay-1307** [comment]
*[ocr.py, line 5 at r1](https://reviewable.io:443/reviews/jay-1307/ocr_project/11#-Kl-quoz6BzgNvXkhktw:-Kl-quoz6BzgNvXkhktx:bynhvgs) ([raw file](https://github.com/jay-1307/ocr_project/blob/5b58d0d64b63990d691662833721824f6aff5621/ocr.py#L5)):*
> ```Python
> #made some changes in reviewable
> #getting no change in reviewable, again trying what else can be done
> #do i need to pull request?? hello
> ```

yeah you need it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jay-1307/ocr_project/11)*

**Comment by jay-1307** [comment]
*[ocr.py, line 5 at r1](https://reviewable.io:443/reviews/jay-1307/ocr_project/11#-Kl-quoz6BzgNvXkhktw:-Kl-qzqt-o1HFuFULG5V:b-896fix) ([raw file](https://github.com/jay-1307/ocr_project/blob/5b58d0d64b63990d691662833721824f6aff5621/ocr.py#L5)):*
<details><summary><i>Previously, jay-1307 wrote…</i></summary><blockquote>

yeah you need it
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jay-1307/ocr_project/11)*

**Comment by jay-1307** [comment]
*[ocr.py, line 5 at r2](https://reviewable.io:443/reviews/jay-1307/ocr_project/11#-Kl-qe2WeNXrNwFd5tUQ:-Kl-qyuu8OfEg7mgx8pv:b-896fix) ([raw file](https://github.com/jay-1307/ocr_project/blob/55d67a984266311ebae50f2c95001e7e9a0b609c/ocr.py#L5)):*
<details><summary><i>Previously, jay-1307 wrote…</i></summary><blockquote>

>  
> #this file contains the python code of our future ocr project.
> #just to see whether it saw changes or not
> #made some changes in reviewable
> #getting no change in reviewable, again trying what else can be done
> #do I need to pull request?? hello
> #man what is happening
> #i came to know that i can only review changes if I do pull request otherwise not
> #hello,what are doing.
>  
>  

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jay-1307/ocr_project/11)*

**Pull request merged**
